server:
  port: 8073
spring:
  application:
    name: trade-service
  config:
    import:
      - nacos:common-config.yaml
  profiles:
    active: local
  cloud:
    nacos:
      server-addr: 192.168.42.138:8848