server:
  port: 8074
spring:
  application:
    name: user-service
  profiles:
    active: dev
  # Import shared configuration from Nacos
  config:
    import:
      - nacos:common-config.yaml
  cloud:
    nacos:
      server-addr: 192.168.42.138:8848
knife4j:
  enable: true
  openapi:
    title: 用户接口文档
    description: "用户接口文档"
    email: zhanghuyi@itcast.cn
    concat: TTTTT
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.user.controller
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /users/login
