server:
  port: 8071
spring:
  application:
    name: pay-service
  profiles:
    active: dev
  # Import shared configuration from Nacos, same as trade-service
  config:
    import:
      - nacos:common-config.yaml
      - nacos:pay-service.yaml
  cloud:
    nacos:
      server-addr: 192.168.42.138:8848
