server:
  port: 8072
spring:
  application:
    name: cart-service
  profiles:
    active: dev
  # Import shared configuration from Nacos
  config:
    import:
      - nacos:common-config.yaml
  cloud:
    nacos:
      server-addr: 192.168.42.138:8848
feign:
  okhttp:
    enabled: true
